lsi: false
safe: true
source: [transformer-model-summaries]
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
# Build settings
markdown: kramdown